# Generated by Django 4.0.4 on 2022-05-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('created_at',), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
